# Site settings
title: Darwin Containers
# email: contact@darwin-containers.org
description: Darwin Containers
url: "https://darwin-containers.github.io"
baseurl: ""

# Build settings
exclude: [".gitignore", "README.md"]
