# Site settings
title: macOS Containers
email: contact@macoscontainers.org
description: macOS Containers
url: "https://macoscontainers.org"
baseurl: ""

# Build settings
exclude: [".gitignore", "README.md"]
